# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QRcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label_qr_code = QtWidgets.QLabel(Dialog)
        self.label_qr_code.setGeometry(QtCore.QRect(10, 10, 461, 461))
        self.label_qr_code.setStyleSheet("background:#ffffff")
        self.label_qr_code.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qr_code.setObjectName("label_qr_code")
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setGeometry(QtCore.QRect(520, 380, 221, 61))
        self.button_cancel.setObjectName("button_cancel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(480, 10, 291, 101))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(480, 110, 291, 101))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color:#ff0000")
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_qr_code.setText(_translate("Dialog", "QRcode"))
        self.button_cancel.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "使用手机APP扫码导入导购清单"))
